name: Build-docker-and-push

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-web-api:v0.1.0

  pull-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull Docker image from Dockerhub
        run: "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple-web-api:v0.1.0"
      - name: Run Docker image
        run: sudo docker run --name web-api-project  -p 5000:3500 -d simple-web-api:v0.1.0
      - name: Test connection to the container
        run: 'curl --header ''Content-Type: application/json'' --request POST --data "{"message":"This is a message."}"'
