name: Simple-Web-API-Project

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: "Use Node ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Installing software dependencies"
        run: "yarn install"

  code-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Installing software dependencies"
        run: "yarn install"
      - name: "Testing format errors."
        run: "yarn format:check"
      - name: "Testing lint errors."
        run: "yarn lint"
